services:
  tailon:
    image: tailon:dev
    container_name: tailon
    command: "--lines-to-tail 100 --lines-of-history 2000 /test.log /non-existing.log"
    volumes:
     - "./test.log:/test.log"
    ports:
     - "9999:8080"